package miEmpresa;
// Generated 9 ene 2024, 19:19:02 by Hibernate Tools 6.2.13.Final

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private int id;
	private String nombre;
	private double precio;

	public Productos() {
	}

	public Productos(int id, String nombre, double precio) {
		this.id = id;
		this.nombre = nombre;
		this.precio = precio;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

}
